# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
    ]
