# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-28 18:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soru', '0002_auto_20200528_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='soru',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
