# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-28 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soru', '0003_auto_20200528_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='HOCA'),
            preserve_default=False,
        ),
    ]
