# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-10 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soru', '0004_soru_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soru',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to=settings.AUTH_USER_MODEL, verbose_name='HOCA'),
        ),
    ]
