# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru', '0005_auto_20200611_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soru',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='soru',
            name='testid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
